defaults:
  - benchmark: gaia-validation
  - override hydra/job_logging: none
  - _self_  # Allow defining variables at the top of this file

entrypoint: main_agent
main_agent:
  name: main_agent
  type: IterativeAgentWithToolAndRollback                           
  llm: 
    _base_: config/llm/base_openai.yaml
    provider_class: GPT5OpenAIClient
    model_name: gpt-5
    max_tokens: 128000
  prompt: config/prompts/prompt_main_agent.yaml
  tools:
    # - config/tool/tool-searching.yaml
    # - config/tool/tool-image-video.yaml
    # - config/tool/tool-reading.yaml
    # - config/tool/tool-code.yaml
    - config/tool/tool-audio.yaml
    # - config/tool/tool-reasoning.yaml
  skills:
    - miroflow/skill/skills/Today_feeling
    - miroflow/skill/skills/Afternoon_feeling
  input_processor:
    - ${input-hint-generator} 
    - ${input-message-generator}
  output_processor:
    - ${output-summary}
    - ${output-final-answer-extraction}
  
input-hint-generator:
  type: InputHintGenerator
  llm:
    _base_: config/llm/base_openai.yaml
    model_name: o3
input-message-generator:
  type: InputMessageGenerator
output-summary:
  type: SummaryGenerator
output-final-answer-extraction:
  type: FinalAnswerExtractor
  prompt: config/prompts/prompt_final_answer_extraction.yaml
  llm:
    _base_: config/llm/base_openai.yaml
    model_name: o3
  #llm o3 TODO


output_dir: logs/
data_dir: "${oc.env:DATA_DIR,data}"  # Points to where data is stored


