# config/benchmark/gaia-validation-165.yaml
defaults:
  - default
  - _self_

name: "gaia-validation-165"

data:
  data_dir: "${data_dir}/gaia-val"

execution:
  max_tasks: null
  max_concurrent: 3
  pass_at_k: 1
  max_retry: 5
  exceed_max_turn_summary: true

openai_api_key: "${oc.env:OPENAI_API_KEY,???}"
openai_base_url: "${oc.env:OPENAI_BASE_URL,https://api.openai.com/v1}"
