# config/llm/base.yaml
provider_class: "MiroThinkerSGLangClient"
model_name: mirothinker-v1.5
api_key: ${oc.env:OAI_MIROTHINKER_API_KEY,???}
base_url: ${oc.env:OAI_MIROTHINKER_BASE_URL,http://localhost:9000/v1}

temperature: 1.0
top_p: 0.95
min_p: 0.0
top_k: -1

max_tokens: 16384
max_context_length: 262144
async_client: true

reasoning_effort: null
repetition_penalty: 1.05

disable_cache_control: false
keep_tool_result: 5
strip_think_from_history: false

use_tool_calls: false
oai_tool_thinking: false
