# SPDX-FileCopyrightText: 2025 MiromindAI
#
# SPDX-License-Identifier: Apache-2.0

"""
Final answer extractor - extracts the final answer from summaries
"""

from miroflow.io_processor.base import BaseIOProcessor
from miroflow.agents.context import AgentContext
from miroflow.registry import register, ComponentType
from miroflow.utils.summary_utils import (
    extract_gaia_final_answer,
    extract_browsecomp_zh_final_answer,
)


@register(ComponentType.IO_PROCESSOR, "FinalAnswerExtractor")
class FinalAnswerExtractor(BaseIOProcessor):
    """Final answer extractor"""

    USE_PROPAGATE_MODULE_CONFIGS = ("llm", "prompt")

    @staticmethod
    def _extract_boxed_content(text: str) -> str:
        """
        Extract content from \\boxed{} patterns in the text.
        Uses balanced brace counting to handle arbitrary levels of nested braces correctly.
        Returns the last matched content, or empty string if no match found.
        """
        if not text:
            return ""

        matches = []
        i = 0

        while i < len(text):
            # Find the next \boxed{ pattern
            boxed_start = text.find(r"\boxed{", i)
            if boxed_start == -1:
                break

            # Start after the opening brace
            content_start = boxed_start + 7  # len(r'\boxed{') = 7
            if content_start >= len(text):
                break

            # Count balanced braces
            brace_count = 1
            content_end = content_start

            while content_end < len(text) and brace_count > 0:
                char = text[content_end]
                if char == "{":
                    brace_count += 1
                elif char == "}":
                    brace_count -= 1
                content_end += 1

            # If we found a balanced match (brace_count == 0)
            if brace_count == 0:
                content = text[
                    content_start : content_end - 1
                ]  # -1 to exclude the closing brace
                matches.append(content)
                # Continue searching from after this complete match
                i = content_end
            else:
                # If braces are unbalanced, skip this \boxed{ and continue searching
                i = content_start

        return matches[-1] if matches else ""

    @staticmethod
    def _format_final_summary_and_log(extracted_answer):
        summary_lines = []
        summary_lines.append("\n" + "=" * 30 + " Final Answer " + "=" * 30)
        summary_lines.append(extracted_answer or "")

        # Extract boxed result - find the last match using safer regex patterns
        boxed_result = FinalAnswerExtractor._extract_boxed_content(extracted_answer)

        # Add extracted result section
        summary_lines.append("\n" + "-" * 20 + " Extracted Result " + "-" * 20)

        if boxed_result:
            summary_lines.append(boxed_result)
        elif extracted_answer:
            summary_lines.append("No \\boxed{} content found.")
            boxed_result = (
                "Final response is generated by LLM, but no \\boxed{} content found."
            )
        else:
            summary_lines.append("No \\boxed{} content found.")
            boxed_result = "No final answer generated."

        return "\n".join(summary_lines), boxed_result

    async def run_internal(self, ctx: AgentContext) -> AgentContext:
        if "browsecomp-zh" in ctx.get("task_meta", {}).get("dataset_name", ""):
            extract_final_answer_function = extract_browsecomp_zh_final_answer
        else:
            extract_final_answer_function = extract_gaia_final_answer

        extracted_answer = await extract_final_answer_function(
            task_description_detail=ctx.get("task_description", ""),
            summary=ctx.get("summary", None),
            llm_client=self.llm_client,
        )

        _, boxed_result = FinalAnswerExtractor._format_final_summary_and_log(
            extracted_answer
        )

        return AgentContext(
            llm_extracted_final_answer=extracted_answer, final_boxed_answer=boxed_result
        )
